import org.apache.tools.ant.filters.FixCrLfFilter

import java.nio.file.Files
import java.nio.file.Paths

apply plugin: 'com.android.library'
apply from: file(rootProject.file('module.gradle'))

android {
    namespace = "zygisk.il2cppdumper"
    compileSdk = rootProject.ext.targetSdk
    ndkVersion = '28.2.13676358'

    defaultConfig {
        minSdk = rootProject.ext.minSdk
        targetSdk = rootProject.ext.targetSdk

        externalNativeBuild {
            cmake {
                arguments("-DMODULE_NAME:STRING=$moduleLibraryName")
            }
        }
    }

    buildFeatures {
        prefab = true
    }

    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            version = "4.1.2"
        }
    }
}

repositories {
    mavenLocal()
}

androidComponents {
    onVariants(selector().all()) { variant ->
        def variantCapped = variant.name.capitalize()
        def variantLowered = variant.name.toLowerCase()

        def zipName = "${moduleName.replace(' ', '_')}-${moduleVersion}(${moduleVersionCode})-${variantLowered}.zip"
        def magiskDir = file("$outDir/magisk_module_$variantLowered")

        tasks.register("prepareMagiskFiles${variantCapped}", Sync) {
            dependsOn("assemble$variantCapped")

            def templatePath = "$rootDir/template/magisk_module"

            into magiskDir
            from(templatePath) {
                exclude 'module.prop'
            }

            from(templatePath) {
                include 'module.prop'
                expand([
                        id         : magiskModuleId,
                        name       : moduleName,
                        version    : moduleVersion,
                        versionCode: moduleVersionCode.toString(),
                        author     : moduleAuthor,
                        description: moduleDescription,
                ])
                filter(FixCrLfFilter.class,
                        eol: FixCrLfFilter.CrLf.newInstance("lf"))
            }

            from(layout.buildDirectory.dir("intermediates/stripped_native_libs/$variantLowered/out/lib")) {
                into 'lib'
            }

            def zygiskDirFile = new File(magiskDir, "zygisk")
            def libDirFile = new File(magiskDir, "lib")
            def magiskLibTree = fileTree(libDirFile)
            def magiskShTree = fileTree(magiskDir).matching { include '**/*.sh' }
            def libName = moduleLibraryName

            doLast {
                zygiskDirFile.mkdir()
                magiskLibTree.visit { f ->
                    if (!f.directory) return
                    def srcPath = Paths.get("${f.file.absolutePath}/lib${libName}.so")
                    def dstPath = Paths.get("${zygiskDirFile.absolutePath}/${f.path}.so")
                    Files.move(srcPath, dstPath)
                }
                libDirFile.deleteDir()

                // Set executable permissions for shell scripts
                magiskShTree.each {
                    it.setExecutable(true, false)
                }
            }
        }

        tasks.register("zip${variantCapped}", Zip) {
            dependsOn("prepareMagiskFiles${variantCapped}")
            from magiskDir
            archiveFileName.set(zipName)
            destinationDirectory.set(outDir)
        }

        tasks.register("push${variantCapped}", Exec) {
            dependsOn("zip${variantCapped}")
            workingDir outDir
            commandLine android.adbExecutable, "push", zipName, "/data/local/tmp/"
        }

        tasks.register("flash${variantCapped}", Exec) {
            dependsOn("push${variantCapped}")
            commandLine android.adbExecutable, "shell", "su", "-c",
                    "magisk --install-module /data/local/tmp/${zipName}"
        }

        tasks.register("flashAndReboot${variantCapped}", Exec) {
            dependsOn("flash${variantCapped}")
            commandLine android.adbExecutable, "shell", "reboot"
        }

        afterEvaluate {
            tasks.named("assemble${variantCapped}").configure {
                finalizedBy("zip${variantCapped}")
            }
        }
    }
}